# apps.conf

# NautilusPreviewer
windowrule = float, class:(org.gnome.NautilusPreviewer)
windowrule = pin, class:(org.gnome.NautilusPreviewer)

# Waypaper
windowrule = float, class:(.*waypaper.*)
windowrule = size 900 700,class:(.*waypaper.*)
windowrule = center, class:(.*waypaper.*)
windowrule = pin, class:(.*waypaper.*)

# Gnome Calendar
windowrule = float, class:(org.gnome.Calendar)
windowrule = pin, class:(org.gnome.Calendar)
windowrule = size 450 550,class:(org.gnome.Calendar)
windowrule = move 100%-w-16 80,class:(org.gnome.Calendar)

# System Mission Center
windowrule = float, class:(io.missioncenter.MissionCenter)
windowrule = pin, class:(io.missioncenter.MissionCenter)
windowrule = center, class:(io.missioncenter.MissionCenter)
windowrule = size 1200 800, class:(io.missioncenter.MissionCenter)

# System Mission Center Preference Window
windowrule = float, class:(missioncenter), title:^(Preferences)$
windowrule = pin, class:(missioncenter), title:^(Preferences)$
windowrule = center, class:(missioncenter), title:^(Preferences)$

# Clash Verge
windowrule = float, class:(clash-verge)
windowrule = pin, class:(clash-verge)
windowrule = center, class:(clash-verge)
windowrule = size 1000 700, class:(clash-verge)

# Clash Nyanpasu
windowrule = float, class:(clash-nyanpasu)
windowrule = pin, class:(clash-nyanpasu)
windowrule = center, class:(clash-nyanpasu)
windowrule = size 1000 700, class:(clash-nyanpasu)

# Gnome Calculator
windowrule = float,class:(org.gnome.Calculator)
windowrule = size 700 600,class:(org.gnome.Calculator)
windowrule = center,class:(org.gnome.Calculator)

# nwg-look
windowrule = float,class:(nwg-look)
windowrule = size 700 600,class:(nwg-look)
windowrule = move 10% 20%,class:(nwg-look)

# windowrule = fullscreen,class:Safeeyes

# disable fullscreen for 绝区零
# windowrule = float, class:(steam_proton), title:^(绝区零)$
# windowrule = center, class:(steam_proton), title:^(绝区零)$
# windowrule = tile, class:(steam_proton), title:^(绝区零)$

windowrule = immediate, initialTitle:^Minecraft\* 1\.\d+\.\d+$

windowrule = noblur,class:^(wechat)$,title:^(wechat)$
windowrule = float,class:^(wechat)$,initialTitle:^(预览)$
windowrule = size 900 700,class:^(wechat)$,initialTitle:^(预览)$

windowrule = move 0 0,class:(flameshot),title:(flameshot)
windowrule = pin,class:(flameshot),title:(flameshot)
windowrule = fullscreenstate,class:(flameshot),title:(flameshot)
windowrule = float,class:(flameshot),title:(flameshot)
