# ML4W Sidebar floating
windowrulev2 = float, class:(com.ml4w.sidebar)
windowrulev2 = pin, class:(com.ml4w.sidebar)
windowrulev2 = size 400 726,class:(com.ml4w.sidebar)
windowrulev2 = move 100%-w-16 66,class:(com.ml4w.sidebar)

windowrule = tile,^(Microsoft-edge)$
windowrule = tile,^(Brave-browser)$
windowrule = tile,^(Chromium)$

# Gnome Calendar
windowrulev2 = float, class:(org.gnome.Calendar)
windowrulev2 = pin, class:(org.gnome.Calendar)
windowrulev2 = size 450 550,class:(org.gnome.Calendar)
windowrulev2 = move 100%-w-16 80,class:(org.gnome.Calendar)

# System Mission Center
windowrulev2 = float, class:(io.missioncenter.MissionCenter)
windowrulev2 = pin, class:(io.missioncenter.MissionCenter)
windowrulev2 = center, class:(io.missioncenter.MissionCenter)
windowrulev2 = size 900 600, class:(io.missioncenter.MissionCenter)

# System Mission Center Preference Window
windowrulev2 = float, class:(missioncenter), title:^(Preferences)$
windowrulev2 = pin, class:(missioncenter), title:^(Preferences)$
windowrulev2 = center, class:(missioncenter), title:^(Preferences)$

# Gnome Calculator
windowrulev2 = float,class:(org.gnome.Calculator)
windowrulev2 = size 700 600,class:(org.gnome.Calculator)
windowrulev2 = center,class:(org.gnome.Calculator)

# nwg-look
windowrulev2 = float,class:(nwg-look)
windowrulev2 = size 700 600,class:(nwg-look)
windowrulev2 = move 10% 20%,class:(nwg-look)
# windowrulev2 = pin,class:(nwg-look)

# gtk-layer-shell
# layerrule = blur ,gtk-layer-shell
# layerrule = ignorezero ,gtk-layer-shell

windowrulev2 = fullscreen,class:Safeeyes

# disable fullscreen for 绝区零

windowrulev2 = float, class:(steam_proton), title:^(绝区零)$
windowrulev2 = center, class:(steam_proton), title:^(绝区零)$
windowrulev2 = tile, class:(steam_proton), title:^(绝区零)$
