# -----------------------------------------------------
# Window rules
# -----------------------------------------------------
windowrule = plugin:hyprbars:nobar, ^floating:0

# windowrule = float,^(blueman-manager)$
# windowrule = float,^(nm-connection-editor)$
# windowrule = float,^(qalculate-gtk)$

# Emoji Picker Smile
windowrule = float,class:(it.mijorus.smile)
windowrule = pin, class:(it.mijorus.smile)
windowrule = move 100%-w-40 90,class:(it.mijorus.smile)

# Hyprland Share Picker
windowrule = float, class:(hyprland-share-picker)
windowrule = pin, class:(hyprland-share-picker)
windowrule = center, title:class:(hyprland-share-picker)
windowrule = size 600 400,class:(hyprland-share-picker)

# Pavucontrol floating
windowrule = float,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = size 950 750,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = center,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = pin,class:(.*org.pulseaudio.pavucontrol.*)

# waybar
layerrule = blur, waybar
layerrule = ignorealpha 0.1, waybar

# SwayNC
layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.6, swaync-notification-window

# Browser Picture in Picture
windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = move 69.5% 4%, title:^(Picture-in-Picture)$

windowrule = float, title:^(画中画)$
windowrule = pin, title:^(画中画)$
windowrule = move 69.5% 4%, title:^(画中画)$

# For XWayland apps
windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$
windowrule = nofocus, class:^(xwaylandvideobridge)$

# windowrule = float, class:^(flameshot)$
# windowrule = move 0 0, class:^(flameshot)$
# windowrule = pin, class:^(flameshot)$
# windowrule = monitor 0, class:^(flameshot)$
# bind = SUPER,S, exec, XDG_CURRENT_DESKTOP=sway flameshot gui
windowrulev2 = noblur,class:^()$,title:^()$ 
