#!/bin/bash

#
# Alias
#

alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

alias c='clear'
alias ff='fastfetch'
alias shutdown='systemctl poweroff'
alias v='$EDITOR'

alias gs="git status"
alias ga="git add -A"
alias gc="git commit -v"
alias gc!="git commit -v --amend --no-edit"
alias gl="git pull"
alias gp="git push"
alias gp!="git push --force"
alias gcl="git clone --depth 1 --single-branch"
alias gf="git fetch --all"
alias gb="git branch"
alias gr="git rebase"
alias gt='cd "$(git rev-parse --show-toplevel)"'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias ipa='ip -br a'
alias rmi='rm -I'
alias tree='tree -aC'
alias r='yy'
alias p='prime-run'
alias ipy='ipython'
alias code.='code .'

if [ "$(command -v win32yank.exe)" ]; then
	alias pbcopy='win32yank.exe -i --crlf'
	alias pbpaste='win32yank.exe -o --lf'
fi

# enable aliases in sudo
alias sudo='sudo '
# let sudo inherit the PATH
alias sudop='command sudo env PATH="$PATH"'

alias proxychains='proxychains '
alias proxychains4='proxychains4 '

if [ "$(command -v nala)" ]; then
	alias apt="nala"
fi

# 先检测并设置 dircolors，为所有支持的命令设置颜色输出
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	alias diff='diff --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'
	alias ip='ip --color=auto'
fi

if [ "$(command -v lsd)" ]; then
	alias ls="lsd --date +%Y%m%d' '%H:%M"
	alias l="lsd -AF"
	alias ll="lsd -alF"
	alias la="lsd -A"
	alias tree="lsd --tree"
elif [ -x /usr/bin/dircolors ]; then
	alias ls='ls --color=auto'
	alias l='ls -CF --color=auto'
	alias ll='ls -alF --color=auto'
	alias la='ls -A --color=auto'
fi

if [ "$(command -v eza)" ]; then
	alias l="eza -a --icons --group-directories-first"
	alias ll="eza -al --icons --group-directories-first"
	alias tree="eza --tree --icons --group-directories-first"
	alias ld="eza -lD"                                         # lists only directories
	alias lf="eza -lF --color=always | grep -v /"              # lists only files (no directories)
	alias gs=eza_gs
fi

if [ "$(command -v trash-put)" ]; then
	alias rm='echo "You should not use rm directly, use trash-put instead." && rm -I'
	alias trm="trash-put"
	alias tls="trash-list"
	alias trs="trash-restore"
fi

if [ "$(command -v bat)" ]; then
	# apt need to set up a bat -> batcat symlink: ln -s /usr/bin/batcat ~/.local/bin/bat
	alias cat="bat"
fi

alias update-grub='grub-mkconfig -o /boot/grub/grub.cfg'
alias startlp='sudo systemctl start tlp.service'
