group {
  groupbar {
      font_size = 11
      col.active = 0x666000000
      col.inactive = 0x66000000
    }
		# gap_tabbar = 0
    col.border_active = 0x66000000
    col.border_inactive = 0x66000000
}

