# tmux like keybindings for resizing and moving windows
bind = SUPER, S ,exec, hyprctl dispatch submap ctl & sleep 3 && hyprctl dispatch submap reset
submap = ctl

binde = , h, movefocus, l
binde = , l, movefocus, r
binde = , k, movefocus, u
binde = , j, movefocus, d

binde = SHIFT, h, resizeactive, l
binde = SHIFT, l, resizeactive, r
binde = SHIFT, k, resizeactive, u
binde = SHIFT, j, resizeactive, d

binde = , n, workspace, e+1
binde = , p, workspace, e-1

binde = , 1, workspace, 1
binde = , 2, workspace, 2
binde = , 3, workspace, 3
binde = , 4, workspace, 4
binde = , 5, workspace, 5
binde = , 6, workspace, 6
binde = , 7, workspace, 7
binde = , 8, workspace, 8
binde = , 9, workspace, 9
binde = , 0, workspace, 10

binde = SHIFT, 1, movetoworkspace, 1
binde = SHIFT, 2, movetoworkspace, 2
binde = SHIFT, 3, movetoworkspace, 3
binde = SHIFT, 4, movetoworkspace, 4
binde = SHIFT, 5, movetoworkspace, 5
binde = SHIFT, 6, movetoworkspace, 6
binde = SHIFT, 7, movetoworkspace, 7
binde = SHIFT, 8, movetoworkspace, 8
binde = SHIFT, 9, movetoworkspace, 9
binde = SHIFT, 0, movetoworkspace, 10

binde = CTRL, 1, exec, $HYPRSCRIPTS/moveTo.sh 1
binde = CTRL, 2, exec, $HYPRSCRIPTS/moveTo.sh 2
binde = CTRL, 3, exec, $HYPRSCRIPTS/moveTo.sh 3
binde = CTRL, 4, exec, $HYPRSCRIPTS/moveTo.sh 4
binde = CTRL, 5, exec, $HYPRSCRIPTS/moveTo.sh 5
binde = CTRL, 6, exec, $HYPRSCRIPTS/moveTo.sh 6
binde = CTRL, 7, exec, $HYPRSCRIPTS/moveTo.sh 7
binde = CTRL, 8, exec, $HYPRSCRIPTS/moveTo.sh 8
binde = CTRL, 9, exec, $HYPRSCRIPTS/moveTo.sh 9
binde = CTRL, 0, exec, $HYPRSCRIPTS/moveTo.sh 10

binde = SUPER, Tab, changegroupactive, f
binde = SUPER SHIFT, Tab, changegroupactive, b
binde = , Tab, workspace, m+1 # Open next workspace
binde = SHIFT, Tab, workspace, m-1 # Open previous workspace
binde = , mouse_down, workspace, e+1 # Open next workspace
binde = , mouse_up, workspace, e-1 # Open previous workspace

binde = , c, exec, uwsm-app alacritty-sock.sh || alacritty-sock.sh

# use reset to go back to the global submap
bind = , escape, submap, reset
bind = , q, submap, reset
bind = CTRL, c, submap, reset
bind = SUPER, escape, submap, reset

submap = reset

