# gromit-mpx
bind = SUPER CTRL,  D,       togglespecialworkspace, gromit
bind = SUPER CTRL,  D,       exec, gromit-mpx --toggle
bind = SUPER CTRL,  D,       submap, gromit
submap = gromit
bind = SHIFT,       F9,      exec, gromit-mpx --clear
bind = ,            F9,      exec, gromit-mpx --toggle
bind = SHIFT,       F8,      exec, gromit-mpx --redo
bind = ,            F8,      exec, gromit-mpx --undo

bind = ALT,         F9,      exec, gromit-mpx --quit
bind = ALT,         F9,      togglespecialworkspace, gromit
bind = ALT,         F9,      submap, reset

bind = CTRL,        F9,      exec, gromit-mpx --toggle
bind = CTRL,        F9,      togglespecialworkspace, gromit
bind = CTRL,        F9,      submap, reset

bind = SUPER CTRL , D,       exec, gromit-mpx --toggle
bind = SUPER CTRL,  D,       togglespecialworkspace, gromit
bind = SUPER CTRL , D,       submap, reset

bind = SUPER,       ESCAPE,  submap, reset
submap = reset
