theme {
    color_scheme = ~/.local/share/color-schemes/LibadwaitaDark.colors

    # style = kvantum

    icon_theme = Tela-dark
    font = 苹方-简
    font_fixed = 更纱黑体 SC
    font_size = 11
    font_fixed_size = 11
}
