# hyprland-nonsystemd.conf

$HYPRSCRIPTS = ~/.config/hypr/scripts

source = ~/.config/hypr/conf/monitor.conf

source = ~/.cache/wal/colors-hyprland.conf

source = ~/.config/hypr/conf/input.conf

source = ~/.config/hypr/conf/layout.conf

source = ~/.config/hypr/conf/windowrule.conf

source = ~/.config/hypr/conf/workspace.conf

source = ~/.config/hypr/conf/keybindings.conf

source = ~/.config/hypr/conf/gestures.conf

source = ~/.config/hypr/conf/plugins.conf

source = ~/.config/hypr/conf/etc/*.conf

env = LANG, zh_CN.UTF-8
env = XDG_MENU_PREFIX, Hyprland-
env = XCURSOR_SIZE, 32
env = XCURSOR_THEME, Bibata-Modern-Ice

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP

exec-once = swww-daemon & disown && crudini --set ~/.config/waypaper/config.ini Settings backend swww && waypaper --restore
exec-once = $HYPRSCRIPTS/gtk.sh
exec-once = xrdb -merge ~/.config/.Xresources
exec-once = wl-paste --watch cliphist store
exec-once = hyprswitch init --show-title
exec-once = ~/.config/nwg-dock-hyprland/nwg-dock-hyprland
exec-once = swayosd-server

# non-systemd
exec-once = hypridle
exec-once = hyprsunset
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ~/.config/waybar/start.sh
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = fcitx5 -d -r

unbind = SUPER CTRL, RETURN
unbind = ALT, SPACE
bind = SUPER CTRL, RETURN,   exec, pkill rofi || rofi -show drun -replace -i
bind = ALT, SPACE,              exec, pkill rofi || rofi -show drun -replace -i

