# hyprland-nonsystemd.conf

$HYPRSCRIPTS = ~/.config/hypr/scripts

source = conf/monitor.conf

source = ~/.cache/wal/colors-hyprland.conf

source = conf/input.conf

source = conf/layout.conf

source = conf/rules.d/*.conf

source = conf/workspace.conf

source = conf/keybindings.conf

source = conf/gestures.conf

source = conf/plugins.conf

source = conf/etc/*.conf

env = LANG, zh_CN.UTF-8
env = XDG_MENU_PREFIX, Hyprland-
env = XCURSOR_SIZE, 32
env = XCURSOR_THEME, Bibata-Modern-Ice

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP LANG

exec-once = swww-daemon
exec-once = $HYPRSCRIPTS/gtk.sh
exec-once = xrdb -merge ~/.config/.Xresources
exec-once = wl-paste --watch cliphist store
exec-once = hyprshell run
exec-once = ~/.config/nwg-dock-hyprland/nwg-dock-hyprland
exec-once = qs -c overview
exec-once = swayosd-server

# non-systemd
exec-once = hypridle
exec-once = hyprsunset
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ~/.config/waybar/start.sh
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = fcitx5 -d -r

unbind = SUPER CTRL, RETURN
unbind = ALT, SPACE
bind = SUPER CTRL, RETURN,   exec, pkill rofi || rofi -show drun -replace -i
bind = ALT, SPACE,              exec, pkill rofi || rofi -show drun -replace -i

