[[shades]]
name = "vibrance"
default = true    # shader to use during times when there is no other shader scheduled

[[shades]]
name = "blue-light-filter-25"
start_time = 19:00:00
end_time = 21:00:00

[[shades]]
name = "blue-light-filter-50"
start_time = 21:00:00
end_time = 00:00:00

[[shades]]
name = "blue-light-filter-50"
start_time = 00:00:00
end_time = 06:00:00
