# hyprland.conf

$HYPRSCRIPTS = ~/.config/hypr/scripts

source = conf/autostart.conf

source = conf/monitor.conf

# source = ~/.config/hypr/noctalia/noctalia-colors.conf
source = ~/.cache/wal/colors-hyprland.conf

source = conf/input.conf

source = conf/layout.conf

source = conf/rules.d/*.conf

source = conf/workspace.conf

source = conf/keybindings.conf

source = conf/gestures.conf

source = conf/plugins.conf

source = conf/etc/*.conf
