# Applications
$BROWSER = zen-browser.desktop
$EDITOR = code.desktop
$FILEMANAGER = org.gnome.Nautilus.desktop
$EMOJIPICKER = it.mijorus.smile.desktop
$CALCULATOR = org.gnome.Calculator.desktop
$TERMINAL = Alacritty.desktop

# Fn keys
bind = , XF86Calculator, exec, uwsm app -- $CALCULATOR
bind = , XF86Tools,      exec, uwsm app -- $TERMINAL

# Keybindings
bind = $mainMod, B,      exec, uwsm app -- $BROWSER
bind = $mainMod ALT, B,  exec, uwsm app -- google-chrome-stable
bind = $mainMod, C,      exec, uwsm app -- $EDITOR
bind = $mainMod, E,      exec, uwsm app -- $FILEMANAGER
bind = $mainMod SHIFT, E,exec, uwsm app -- dolphin
bind = $mainMod CTRL, E, exec, uwsm app -- $EMOJIPICKER
bind = $mainMod CTRL, C, exec, uwsm app -- $CALCULATOR

bind = CTRL ALT,       T,           exec, ~/.local/bin/alacritty-sock.sh
bind = $mainMod,       RETURN,      exec, kitty -1
bind = $mainMod SHIFT, Return,      exec, uwsm app -- com.mitchellh.ghostty.desktop
bind = $mainMod SHIFT CTRL, Return, exec, uwsm app -- org.wezfurlong.wezterm.desktop
# bind = $mainMod,       L,           exec, hyprlock # Open screenlock

binde = $mainMod ALT, Tab, changegroupactive, f
binde = $mainMod SHIFT ALT, Tab, changegroupactive, b

