$mainMod = SUPER

# Applications
$BROWSER = zen
$EDITOR = code
$FILEMANAGER = nautilus
$EMOJIPICKER = smile
$CALCULATOR = gnome-calculator
$TERMINAL = alacritty

# Fn keys
bind = , XF86Calculator, exec, $CALCULATOR
bind = , XF86Tools, exec, $TERMINAL

# Keybindings
bind = $mainMod, B,      exec, uwsm app -- $BROWSER
bind = $mainMod ALT, B,  exec, uwsm app -- google-chrome-stable
bind = $mainMod, C,      exec, uwsm app -- $EDITOR
bind = $mainMod, E,      exec, uwsm app -- $FILEMANAGER
bind = $mainMod SHIFT, E,exec, uwsm app -- dolphin
bind = $mainMod CTRL, E, exec, uwsm app -- $EMOJIPICKER
bind = $mainMod CTRL, C, exec, uwsm app -- $CALCULATOR

bind = CTRL ALT,       T,           exec, ~/.local/bin/alacritty-sock.sh
bind = $mainMod,       RETURN,      exec, kitty -1
bind = $mainMod SHIFT, Return,      exec, ghostty
bind = $mainMod SHIFT CTRL, Return, exec, wezterm
# bind = $mainMod,       L,           exec, hyprlock # Open screenlock

binde = $mainMod ALT, Tab, changegroupactive, f
binde = $mainMod SHIFT ALT, Tab, changegroupactive, b

binds {
    movefocus_cycles_fullscreen = 0
}

# bind = $mainMod, A, movefocus, l # Move focus left
# bind = $mainMod, D, movefocus, r # Move focus right
# bind = $mainMod, W, movefocus, u # Move focus up
# bind = $mainMod, S, movefocus, d # Move focus down


source = submap_ctl.conf
