# hyprlang noerror true
# split-monitor-workspaces
unbind = $mainMod, 1
unbind = $mainMod, 2
unbind = $mainMod, 3
unbind = $mainMod, 4
unbind = $mainMod, 5
unbind = $mainMod, 6
unbind = $mainMod, 7
unbind = $mainMod, 8
unbind = $mainMod, 9
unbind = $mainMod, 0
unbind = $mainMod SHIFT, 1
unbind = $mainMod SHIFT, 2
unbind = $mainMod SHIFT, 3
unbind = $mainMod SHIFT, 4
unbind = $mainMod SHIFT, 5
unbind = $mainMod SHIFT, 6
unbind = $mainMod SHIFT, 7
unbind = $mainMod SHIFT, 8
unbind = $mainMod SHIFT, 9
unbind = $mainMod SHIFT, 0
unbind = $mainMod CTRL, 1
unbind = $mainMod CTRL, 2
unbind = $mainMod CTRL, 3
unbind = $mainMod CTRL, 4
unbind = $mainMod CTRL, 5
unbind = $mainMod CTRL, 6
unbind = $mainMod CTRL, 7
unbind = $mainMod CTRL, 8
unbind = $mainMod CTRL, 9
unbind = $mainMod CTRL, 0
unbind = $mainMod, End
unbind = $mainMod, Home
unbind = $mainMod, Tab
unbind = $mainMod SHIFT, Tab
unbind = $mainMod, mouse_down
unbind = $mainMod, mouse_up
unbind = $mainMod CTRL, down
unbind = $mainMod CTRL, up
unbind = $mainMod CTRL, left
unbind = $mainMod CTRL, right
unbind = $mainMod SHIFT CTRL, down, movetoworkspace, e-1
unbind = $mainMod SHIFT CTRL, up, movetoworkspace, e+1
unbind = $mainMod SHIFT CTRL, left, movetoworkspace, -1
unbind = $mainMod SHIFT CTRL, right, movetoworkspace, +1

#################
### workspace ###
#################

bind = $mainMod, 1, split-workspace, 1
bind = $mainMod, 2, split-workspace, 2
bind = $mainMod, 3, split-workspace, 3
bind = $mainMod, 4, split-workspace, 4
bind = $mainMod, 5, split-workspace, 5
bind = $mainMod, 6, split-workspace, 6
bind = $mainMod, 7, split-workspace, 7
bind = $mainMod, 8, split-workspace, 8
bind = $mainMod, 9, split-workspace, 9
bind = $mainMod, 0, split-workspace, 10

# Move active window to workspace
bind = $mainMod SHIFT, 1, split-movetoworkspace, 1
bind = $mainMod SHIFT, 2, split-movetoworkspace, 2
bind = $mainMod SHIFT, 3, split-movetoworkspace, 3
bind = $mainMod SHIFT, 4, split-movetoworkspace, 4
bind = $mainMod SHIFT, 5, split-movetoworkspace, 5
bind = $mainMod SHIFT, 6, split-movetoworkspace, 6
bind = $mainMod SHIFT, 7, split-movetoworkspace, 7
bind = $mainMod SHIFT, 8, split-movetoworkspace, 8
bind = $mainMod SHIFT, 9, split-movetoworkspace, 9
bind = $mainMod SHIFT, 0, split-movetoworkspace, 10

# Move all windows to workspace
bind = $mainMod CTRL, 1, exec, $HYPRSCRIPTS/moveall-split.sh 1
bind = $mainMod CTRL, 2, exec, $HYPRSCRIPTS/moveall-split.sh 2
bind = $mainMod CTRL, 3, exec, $HYPRSCRIPTS/moveall-split.sh 3
bind = $mainMod CTRL, 4, exec, $HYPRSCRIPTS/moveall-split.sh 4
bind = $mainMod CTRL, 5, exec, $HYPRSCRIPTS/moveall-split.sh 5
bind = $mainMod CTRL, 6, exec, $HYPRSCRIPTS/moveall-split.sh 6
bind = $mainMod CTRL, 7, exec, $HYPRSCRIPTS/moveall-split.sh 7
bind = $mainMod CTRL, 8, exec, $HYPRSCRIPTS/moveall-split.sh 8
bind = $mainMod CTRL, 9, exec, $HYPRSCRIPTS/moveall-split.sh 9
bind = $mainMod CTRL, 0, exec, $HYPRSCRIPTS/moveall-split.sh 10

bind = $mainMod, End, split-workspace, +1
bind = $mainMod, Home, split-workspace, -1
bind = $mainMod, Tab, split-workspace, m+1
bind = $mainMod SHIFT, Tab, split-workspace, m-1

bind = $mainMod, mouse_down, split-workspace, e-1
bind = $mainMod, mouse_up, split-workspace, e+1

bind = $mainMod CTRL, down, split-workspace, e-1
bind = $mainMod CTRL, up, split-workspace, e+1
bind = $mainMod CTRL, left, split-workspace, -1
bind = $mainMod CTRL, right, split-workspace, +1

bind = $mainMod SHIFT CTRL, down, split-movetoworkspace, e-1
bind = $mainMod SHIFT CTRL, up, split-movetoworkspace, e+1
bind = $mainMod SHIFT CTRL, left, split-movetoworkspace, -1
bind = $mainMod SHIFT CTRL, right, split-movetoworkspace, +1

# hyprlang noerror false
