# Fn keys
bindel = , XF86MonBrightnessUp,   exec, swayosd-client --brightness +10                   || brightnessctl -q s +10%
bindel = , XF86MonBrightnessDown, exec, swayosd-client --brightness -10                   || brightnessctl -q s 10%-
bindel = , XF86AudioRaiseVolume,  exec, swayosd-client --output-volume 5 --max-volume 100 || wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume,  exec, swayosd-client --output-volume -5                 || wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = , XF86AudioMute,         exec, swayosd-client --output-volume mute-toggle        || wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl  = , XF86AudioMicMute,      exec, swayosd-client --input-volume mute-toggle         || wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl  = , XF86AudioPlay,         exec, swayosd-client --playerctl play-pause             || playerctl play-pause
bindl  = , XF86AudioStop,         exec, swayosd-client --playerctl stop                   || playerctl stop
bindl  = , XF86AudioPause,        exec, swayosd-client --playerctl pause                  || playerctl pause
bindl  = , XF86AudioNext,         exec, swayosd-client --playerctl next                   || playerctl next
bindl  = , XF86AudioPrev,         exec, swayosd-client --playerctl previous               || playerctl previous
bindl  = , XF86PowerOff,          exec, ~/.config/wleave/toggle.sh
bind   = , Num_Lock,              exec, sleep 0.1 && swayosd-client --num-lock
bindl  = , XF86Lock,              exec, hyprlock

bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off
bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on

# keyboard backlight
bindel = , code:238,              exec, brightnessctl -d smc::kbd_backlight s +10
bindel = , code:237,              exec, brightnessctl -d smc::kbd_backlight s 10-

bind   = $mainMod, semicolon,     exec, hyprlock
# screenshots
bind   = , PRINT,                 exec, grimblast --notify --freeze copy screen
bind   = SHIFT, PRINT,            exec, grimblast --notify --freeze copy output
bind   = $mainMod SHIFT, S,       exec, $HYPRSCRIPTS/screenshot.sh                                # Take a screenshot

# dock
bind   = SUPER, SUPER_L,          exec, pkill nwg-drawer || nwg-dock-hyprland
bind   = SUPER, SUPER_L,          exec, sleep 0.2 && hyprctl dispatch submap reset
bind   = SUPER, SUPER_L,          submap, super_double_press
submap = super_double_press
bind   = SUPER, SUPER_L,          exec, nwg-dock-hyprland && nwg-drawer
submap = reset

# hyprswitch
bind   = ALT, TAB,                exec, hyprswitch gui --mod-key alt_l --key TAB --close mod-key-release --reverse-key=mod=SHIFT && hyprswitch dispatch
bind   = ALT SHIFT, TAB,          exec, hyprswitch gui --mod-key alt_l --key TAB --close mod-key-release --reverse-key=mod=SHIFT && hyprswitch dispatch -r

# Snipaste
bind = , F1,                      exec, Snipaste snip
bind = , F3,                      exec, Snipaste paste

