# Fn keys
bindel = , XF86MonBrightnessUp,   exec, brightnessctl -q s +10%
bindel = , XF86MonBrightnessDown, exec, brightnessctl -q s 10%-
bindel = , XF86AudioRaiseVolume,  exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86AudioMicMute,      exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindl  = , XF86AudioPlay,         exec, playerctl play-pause
bindl  = , XF86AudioStop,         exec, playerctl stop
bindl  = , XF86AudioPause,        exec, playerctl pause
bindl  = , XF86AudioNext,         exec, playerctl next
bindl  = , XF86AudioPrev,         exec, playerctl previous
bindl  = , XF86PowerOff,          exec, ~/.config/wleave/toggle.sh
bindl  = , XF86Lock,              exec, uwsm-app -s s hyprlock || hyprlock

# keyboard backlight
bindel = , code:238,              exec, brightnessctl -d smc::kbd_backlight s +10
bindel = , code:237,              exec, brightnessctl -d smc::kbd_backlight s 10-

bind  = $mainMod, semicolon,     exec, uwsm-app -s s hyprlock || hyprlock                  # lock screen
# screenshots
bind   = , PRINT,                 exec, grimblast --notify --freeze copy screen
bind   = SHIFT, PRINT,            exec, grimblast --notify --freeze copy output
bind   = $mainMod SHIFT, S,       exec, $HYPRSCRIPTS/screenshot.sh                                # Take a screenshot

# dock
bind   = SUPER, SUPER_L,          exec, pkill nwg-drawer || nwg-dock-hyprland
bind   = SUPER, SUPER_L,          exec, sleep 0.2 && hyprctl dispatch submap reset
bind   = SUPER, SUPER_L,          submap, super_double_press
submap = super_double_press
bind   = SUPER, SUPER_L,          exec, nwg-dock-hyprland && nwg-drawer
submap = reset

# hyprswitch
bind   = ALT, TAB,                exec, hyprswitch gui --mod-key alt_l --key TAB --close mod-key-release --reverse-key=mod=SHIFT && hyprswitch dispatch
bind   = ALT SHIFT, TAB,          exec, hyprswitch gui --mod-key alt_l --key TAB --close mod-key-release --reverse-key=mod=SHIFT && hyprswitch dispatch -r

# Snipaste
bind = , F1,                      exec, Snipaste snip
bind = , F3,                      exec, Snipaste paste
