# Utilities
bind = $mainMod, V,             exec, swaync-client -t                                    # Open notification center
# bind = $mainMod SHIFT, V,       exec, pkill fuzzel || cliphist list | fuzzel --match-mode fzf --dmenu | cliphist decode | wl-copy
bind = $mainMod SHIFT, V,       exec, $HYPRSCRIPTS/cliphist.sh                            # Open clipboard manager

bind = $mainMod CTRL, Q,        exec, ~/.config/wleave/toggle.sh                          # Open logout menu
bind = $mainMod ALT, G,         exec, $HYPRSCRIPTS/gamemode.sh                            # Toggle game mode

# waybar
bind = $mainMod SHIFT, B,       exec, systemctl --user reload waybar.service              # Restart waybar
bind = $mainMod CTRL, B,        exec, ~/.config/waybar/toggle.sh                          # Toggle waybar
bind = $mainMod SHIFT CTRL, B,  exec, ~/.config/waybar/themeswitcher.sh                   # Open waybar theme switcher

# launchers
bind = $mainMod CTRL, RETURN,   exec, pkill rofi || rofi -show drun -replace -i -run-command "uwsm-app -- {cmd}"
bind = ALT, SPACE,              exec, pkill rofi || rofi -show drun -replace -i -run-command "uwsm-app -- {cmd}"

# wallpaper
bind = $mainMod SHIFT, W,       exec, waypaper --random
bind = $mainMod SHIFT CTRL, W,  exec, ~/.config/waypaper/waypaper-random-toggle.sh
bind = $mainMod CTRL, W,        exec, uwsm-app waypaper || waypaper

# screenshots
bind   = , PRINT,                 exec, grim - | tee "$(xdg-user-dir PICTURES)/Screenshots/Screenshot_$(date '+%Y%m%d_%H%M%S').png" | wl-copy
bind   = SHIFT, PRINT,            exec, grimblast --notify --freeze copy output
bind   = $mainMod SHIFT, S,       exec, $HYPRSCRIPTS/screenshot.sh

# media keys
bindl = CTRL ALT, p,             exec, swayosd-client --playerctl play-pause || playerctl play-pause
bindl = CTRL ALT, right,         exec, swayosd-client --playerctl next       || playerctl next
bindl = CTRL ALT, left,          exec, swayosd-client --playerctl previous   || playerctl previous
binde = CTRL ALT, up,            exec, playerctl volume 0.1+
binde = CTRL ALT, down,          exec, playerctl volume 0.1-
