# Notice: uwsm-app app daemon is failing on simultaneous requests

# inputactions
exec-once = ln -srf ~/.config/inputactions/config_hyprland.yaml ~/.config/inputactions/config.yaml
# Night Light
exec-once = echo "hyprsunset" > ~/.local/state/sunsetr/default/active_preset
# hyprpaper backend
exec-once = crudini --set ~/.config/waypaper/config.ini Settings backend hyprpaper && waypaper --restore
# kde dialogs
exec-once = crudini --set ~/.config/qt6ct/qt6ct.conf Appearance standard_dialogs kde
# Load GTK settings
# exec-once = $HYPRSCRIPTS/gtk.sh

# Load Xresources
exec-once = xrdb -merge ~/.config/.Xresources

# Load cliphist history
exec-once = runapp -i background.slice -- wl-paste --watch cliphist store

# ALT-TAB
exec-once = runapp -i background-graphical.slice -- hyprswitch init --show-title

exec-once = runapp -i background-graphical.slice -- qs -c overview
# Dock
exec-once = runapp -i background-graphical.slice -- ~/.config/nwg-dock-hyprland/nwg-dock-hyprland

# OSD
exec-once = runapp -i background-graphical.slice -- swayosd-server

# workspace init
exec-once = [workspace 2 silent] runapp -o -- zen
exec-once = [workspace 1 silent] runapp -o -- kitty -1

# for XF86PowerOff key

# hyprlang if XDG_RUNTIME_DIR
exec-once = systemd-inhibit --who="Hyprland config" --why="wleave keybind" --what=handle-power-key --mode=block sleep infinity & echo $! > $XDG_RUNTIME_DIR/.hyprland-systemd-inhibit
exec-shutdown = kill -9 "$(cat $XDG_RUNTIME_DIR/.hyprland-systemd-inhibit)" && rm "$XDG_RUNTIME_DIR/.hyprland-systemd-inhibit"
# hyprlang endif
