gestures {
  workspace_swipe_distance = 500
  workspace_swipe_forever = true
}

# gesture = 3, swipe,                          move
# gesture = 3, swipe,      mod:ALT,            resize
gesture = 4, horizontal,                     workspace
gesture = 4, horizontal, mod:ALT, scale:0.5, special, term
gesture = 4, vertical,                       fullscreen
gesture = 4, down,       mod:ALT,            dispatcher, exec, amixer set Master "8%+"
gesture = 4, up,         mod:ALT,            dispatcher, exec, amixer set Master "8%-"
gesture = 4, pinchin,             scale:0.8, float
gesture = 4, pinchout,                       dispatcher, hyprexpo:expo, toggle
