input {
	numlock_by_default = true
	kb_layout = us
	# kb_variant = intl
	# kb_model = pc105
	# man xkeyboard-config
	kb_options = caps:escape_shifted_capslock,shift:both_capslock,terminate:ctrl_alt_bksp

	# mouse
	follow_mouse = 1
	mouse_refocus = false
	sensitivity = 0.2
	scroll_factor = 1.0 

	special_fallthrough = true
}

input {
	touchpad {
		natural_scroll = true
		middle_button_emulation = true
		clickfinger_behavior = false
		disable_while_typing = true
		scroll_factor = 1.0
	}
}

gestures {
  workspace_swipe = true
  workspace_swipe_fingers = 3
	workspace_swipe_min_fingers = true
  workspace_swipe_distance = 500
  workspace_swipe_forever = true
}

# https://old.reddit.com/r/hyprland/comments/11v6iif/tutorial_making_caps_do_both_control_and_esc_like/
# If using ctrl:nocapsr, both caps and lctrl send Control_L but with different keycodes: caps=66 vs lctrl=37, so we must then use the keycode
#bindr=CONTROL,66,exec, YDOTOOL_SOCKET=/run/user/1001/.ydotool_socket ydotool key 1:1 1:0
# If using caps:ctrl_modifier, it's simpler:
# bindr=CONTROL,Caps_Lock,exec, YDOTOOL_SOCKET=/run/user/1000/.ydotool_socketydotool key 1:1 1:0
# Control_L can also be redefined to whatever, here PageUp
# bindr=CONTROL,Control_L,exec, YDOTOOL_SOCKET=/run/user/1001/.ydotool_socket ydotool key 109:1 109:0
