$mainMod = SUPER

source = ~/.config/hypr/conf/keybindings/binds.conf
source = ~/.config/hypr/conf/keybindings/standalone.conf
source = ~/.config/hypr/conf/keybindings/neccessary.conf
source = ~/.config/hypr/conf/keybindings/apps.conf
source = ~/.config/hypr/conf/keybindings/submaps/*.conf
