$mainMod = SUPER

source = keybindings/binds.conf
source = keybindings/utilities.conf
source = keybindings/standalone.conf
source = keybindings/apps.conf
source = keybindings/submaps/*.conf
source = keybindings/plugins.conf
