general:layout = scrolling

dwindle {
	pseudotile = true
	preserve_split = true
	# smart_split = true
}

master {
	mfact = +0.67
	new_on_top = true
	new_status = master
}

scrolling {
	column_width = 0.7
	follow_min_visible = 0.8
}
