exec-once = hyprpm reload -nn

plugin {
	hyprbars {
		bar_height = 32
		bar_color = rgb(1e1e1e)
		col.text = $foreground
		bar_text_size = 12
		bar_text_font = Jetbrains Mono Nerd Font Mono Bold
		bar_button_padding = 10
		bar_padding = 8
		bar_precedence_over_border = true
		hyprbars-button = $color1, 20, , hyprctl dispatch killactive
		hyprbars-button = $color3, 20, , hyprctl dispatch fullscreenstate 2 0
		hyprbars-button = $color4, 20, , hyprctl dispatch togglefloating
	}
	hyprscrolling {
		column_width = 0.6
		focus_fit_method = 0
	}
	hyprexpo {
		columns = 2
		gap_size = 5
		# bg_col = rgb(111111)
		workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1
		gesture_distance = 300 # how far is the "max" for the gesture
	}
	csgo-vulkan-fix {
		fix_mouse = true
		vkfix-app = cs2, 1650, 1050
	}
	hyprfocus {
		mode = slide
		fade_opacity = 0.85
		only_on_monitor_change = false
	}
}

# hyprlang noerror true
bind = super, W, hyprexpo:expo, toggle

animation = hyprfocusIn, 1, 3.5, myCurve
animation = hyprfocusOut, 1, 2.5, myCurve2
# hyprlang noerror false
