exec-once = hyprpm reload

plugin {
	hyprbars {
		bar_height = 32
		bar_color = $primary_container
		col.text = $on_primary_container
		bar_text_size = 12
		bar_text_font = PingFang SC, Jetbrains Mono Nerd Font Mono Bold
		bar_button_padding = 10
		bar_padding = 8
		bar_precedence_over_border = true
		hyprbars-button = $on_error_container, 20, , hyprctl dispatch killactive
		hyprbars-button = $secondary, 20, 󰖯, hyprctl dispatch fullscreenstate 2 0
		hyprbars-button = $primary, 20, 󰖰, hyprctl dispatch movetoworkspacesilent special
	  hyprbars-button = $on_surface, 14, , hyprctl dispatch togglefloating
	}

	hyprscrolling {
		column_width = 0.6
		focus_fit_method = 0
	}
	hyprexpo {
		columns = 2
		gap_size = 5
		bg_col = $on_surface
		workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1
	}
	csgo-vulkan-fix {
		fix_mouse = true
		vkfix-app = cs2, 1650, 1050
	}
	hyprfocus {
		mode = slide
		fade_opacity = 0.85
		only_on_monitor_change = true
	}
	split-monitor-workspaces:enable_persistent_workspaces = false
}

# hyprlang noerror true

# overview
# hyprtasking Hyprspace
bind = super, G, hyprexpo:expo, toggle

bind = SUPER, W, exec, qs ipc -c overview call overview toggle

animation = hyprfocusIn, 1, 3.5, myCurve
animation = hyprfocusOut, 1, 2.5, myCurve2

# hyprbars for floating windows
windowrule = hyprbars:no_bar on, match:float 0

windowrule = hyprbars:no_bar on, match:initial_class ^wechat$, match:initial_title ^wechat$, match:float 1, match:xwayland 1
# hyprlang noerror false
