# workspace.conf

# special workspace
workspace = special:special, on-created-empty:[float; move 15% 15%; size 70% 70%] alacritty-sock.sh

# gromit annotation workspace
workspace = special:gromit, gapsin:0, gapsout:0, on-created-empty: gromit-mpx

# Smart gaps
workspace = w[tv1], gapsout:7, gapsin:0
workspace = f[1], gapsout:7, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
