[[mgr.prepend_keymap]]
on = "<F3>"
run = '''shell 'ripdrag "$@" -x 2>/dev/null &' --confirm'''

[[mgr.prepend_keymap]]
on  = "<F4>"
run = [ 'shell --orphan -- dolphin .' ]

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/workspaces/"
desc = "Goto workspaces"

[[mgr.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/.local/share/"
desc = "Goto ~/.local/share/"

[[mgr.prepend_keymap]]
on = ["g", "u", "s"]
run = "cd /usr/share/"
desc = "Goto /usr/share/"

[[mgr.prepend_keymap]]
on = ["g", "u", "c"]
run = "cd /etc/"
desc = "Goto /etc/"

# smart-enter.yazi
[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# open-with-cmd
[[mgr.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd block"
desc = "Open with command in the terminal"

[[mgr.prepend_keymap]]
on = "O"
run = "plugin open-with-cmd"
desc = "Open with command"

# toggle-pane.yazi
[[mgr.prepend_keymap]]
on = "t"
run = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on = "<C-t>"
run = "tab_create --current"
description = "Create a new tab with CWD"
