[[manager.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/workspaces/"
desc = "Goto workspaces"

[[manager.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/.local/share/"
desc = "Goto ~/.local/share/"

[[manager.prepend_keymap]]
on = ["g", "u", "s"]
run = "cd /usr/share/"
desc = "Goto /usr/share/"

[[manager.prepend_keymap]]
on = ["g", "u", "c"]
run = "cd /etc/"
desc = "Goto /etc/"

# open-with-cmd
[[manager.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd block"
desc = "Open with command in the terminal"

[[manager.prepend_keymap]]
on = "O"
run = "plugin open-with-cmd"
desc = "Open with command"
