# eza-preview
# [[manager.prepend_keymap]]
# on   = "E"
# run  = "plugin eza-preview"
# desc = "Toggle tree/list dir preview"
# 
# [[manager.prepend_keymap]]
# on   = "-"
# run  = "plugin eza-preview --args='inc-level'"
# desc = "Increment tree level"
# 
# [[manager.prepend_keymap]]
# on   = "_"
# run  = "plugin eza-preview --args='dec-level'"
# desc = "Decrement tree level"
# 
# [[manager.prepend_keymap]]
# on   = "$"
# run  = "plugin eza-preview --args='toggle-follow-symlinks'"
# desc = "Toggle tree follow symlinks"

# open-with-cmd
[[manager.prepend_keymap]]
on   = "o"
run  = "plugin open-with-cmd --args=block"
desc = "Open with command in the terminal"

[[manager.prepend_keymap]]
on   = "O"
run  = "plugin open-with-cmd"
desc = "Open with command"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --sync hide-preview"
# For upcoming Yazi 0.4 (nightly version):
# run  = "plugin hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on = [ "g", "s" ]
run = "cd ~/.local/share/"
desc = "Goto ~/.local/share/"

[[manager.prepend_keymap]]
on = [ "g", "u", "s" ]
run = "cd /usr/share/"
desc = "Goto /usr/share/"

[[manager.prepend_keymap]]
on = [ "g", "u", "c" ]
run = "cd /etc/"
desc = "Goto /etc/"
