# --proxy-server=
--disable-gpu-driver-bug-workarounds
--enable-features=VaapiVideoDecodeLinuxGL,UseChromeOSDirectVideoDecoder,CanvasOopRasterization,WebUIDarkMode
--disable-features=GlobalShortcutsPortal
--enable-gpu-rasterization
--ignore-gpu-blocklist
--ozone-platform-hint=auto
--enable-wayland-ime
--wayland-text-input-version=3
--silent-debugger-extension-api
--password-store=detect
# password-store=<basic|gnome-libsecret|kwallet6|detect>
