[general]
import = ['./themes/catppuccin/catppuccin-macchiato.toml']
live_config_reload = true

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM_PROGRAM = "alacritty"
WSLENV = "TERM:COLORTERM:TERM_PROGRAM"

[font]
size = 12

[font.bold]
family = "MonaspiceNe Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspiceNe Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonaspiceNe Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"
# family = "MonaspiceNe Nerd Font"
# family = "Maple Mono"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 20

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.85
# startup_mode = "Maximized"

[window.dimensions]
columns = 135
lines = 40

[window.padding]
x = 10
y = 15

# [window.position]
# x = 200
# y = 200

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "CreateNewWindow" },
   { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]
