[general]
import = ['./themes/catppuccin/catppuccin-macchiato.toml']
live_config_reload = true

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM_PROGRAM = "alacritty"
WSLENV = "TERM:COLORTERM:TERM_PROGRAM"

[colors]
# transparent_background_colors = true

[font]
size = 12

[font.bold]
family = "MonaspiceNe Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspiceNe Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonaspiceNe Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"
# family = "MonaspiceNe Nerd Font"
# family = "Maple Mono"

[font.offset]
x = 0
y = 0


[scrolling]
history = 10000
multiplier = 20

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.85
blur = true
# startup_mode = "Maximized"

[window.dimensions]
columns = 135
lines = 40

[window.padding]
x = 10
y = 15

# [window.position]
# x = 200
# y = 200

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[keyboard]

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Shift"
mode = "~Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Shift"
mode = "~Vi|~Search"
action = "SearchBackward"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Shift"
mode = "~Vi|~Search"
chars = "❯"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Shift"
mode = "~Vi|~Search"
action = "SearchConfirm"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Shift"
mode = "Vi"
action = "SearchBackward"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Shift"
mode = "Vi"
chars = "❯"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Shift"
mode = "Vi"
action = "SearchConfirm"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Shift"
mode = "~Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Shift"
mode = "~Vi|~Search"
action = "SearchForward"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Shift"
mode = "~Vi|~Search"
chars = "❯"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Shift"
mode = "~Vi|~Search"
action = "SearchConfirm"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Shift"
mode = "Vi"
action = "SearchForward"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Shift"
mode = "Vi"
chars = "❯"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Shift"
mode = "Vi"
action = "SearchConfirm"

# CSI u
# Tab 相关
[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001b[9;5u"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u001b[9;6u"

# 方向键
[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[68;5u"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[67;5u"

[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[65;5u"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[66;5u"

# 常用功能键
[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001b[13;5u"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u001b[32;5u"


# Ctrl+Shift 组合
[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
chars = "\u001b[84;6u"

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
chars = "\u001b[87;6u"
