[general]
import = ['~/.config/alacritty/catppuccin/catppuccin-macchiato.toml']
live_config_reload = true

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM_PROGRAM = "alacritty"
WSLENV = "TERM:COLORTERM:TERM_PROGRAM"

[font]
size = 12

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 20

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.85
# startup_mode = "Maximized"

[window.dimensions]
columns = 135
lines = 40

[window.padding]
x = 10
y = 15

# [window.position]
# x = 200
# y = 200
