# apps.conf

# Hyprland Share Picker
# windowrule = float on, pin on, size 600 400, match:class (hyprland-share-picker)
# windowrule = center on, match:class (hyprland-share-picker)

# Pavucontrol floating
windowrule = float on, size 950 750, center on, pin on, match:class (.*org.pulseaudio.pavucontrol.*)

# Emoji Picker Smile
windowrule = float on, pin on, move ((monitor_w*1)-window_w-40) (90), match:class (it.mijorus.smile)

# NautilusPreviewer
windowrule = float on, pin on, match:class (org.gnome.NautilusPreviewer)

# Waypaper
windowrule = float on, size 900 700, center on, pin on, match:class (.*waypaper.*)

# Gnome Calendar
windowrule = float on, pin on, size 450 550, move ((monitor_w*1)-window_w-16) (80), match:class (org.gnome.Calendar)

# System Mission Center
windowrule = float on, pin on, center on, size 1200 800, match:class (io.missioncenter.MissionCenter)

# System Mission Center Preference Window
windowrule = float on, pin on, center on, match:class (missioncenter), match:title ^(Preferences)$

# Clash Verge
windowrule = float on, pin on, center on, size 1000 700, match:class (clash-verge)

# Clash Nyanpasu
windowrule = float on, pin on, center on, size 1000 700, match:class (clash-nyanpasu)

# Gnome Calculator
windowrule = float on, size 700 600, center on, match:class (org.gnome.Calculator)

# nwg-look
windowrule = float on, size 700 600, move ((monitor_w*0.1)) ((monitor_h*0.2)), match:class (nwg-look)


# workaround for apps misbehaving

# flameshot anotation window
windowrule = pin on, float on, match:class (flameshot), match:title (flameshot)

# games
windowrule = immediate on, match:initial_title ^Minecraft\* 1\.\d+\.\d+$

# xwayland apps
# wechat xwayland blur issue
windowrule = no_blur on, match:class ^(wechat)$, match:title ^(wechat)$
windowrule = float on, size 900 700, match:class ^(wechat)$, match:initial_title ^(预览)$

# Gromit-mpx
windowrule = no_blur on, opacity 1 override, no_shadow on, fullscreen_state 1 0, match:class ^(Gromit-mpx)$
# windowrule = size 100% 100%, class:^(Gromit-mpx)$

# disable fullscreen for 绝区零
# windowrule = float, class:(steam_proton), title:^(绝区零)$
# windowrule = center, class:(steam_proton), title:^(绝区零)$
# windowrule = tile, class:(steam_proton), title:^(绝区零)$

