# global.conf

# hyprbars for floating windows
windowrule = hyprbars:no_bar on, match:float 0
# Ignore maximize requests from apps.
windowrule = suppress_event maximize, match:class .*

# XWayland
# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
# Fix popups widgets blur around borders
windowrule = no_blur on, match:class ^$, match:title ^$, match:xwayland 1

# xwaylandvideobridge
windowrule = opacity 0.0 override, no_anim on, no_initial_focus on, max_size 1 1, no_blur on, no_focus on, match:class ^(xwaylandvideobridge)$

# Browser Picture in Picture
windowrule = float on, pin on, move ((monitor_w*0.695)) ((monitor_h*0.04)), match:title ^(Picture-in-Picture)$

windowrule = float on, pin on, move ((monitor_w*0.695)) ((monitor_h*0.04)), match:title ^(画中画)$

