# layerrule.conf

# waybar
layerrule = blur on, ignore_alpha 0.1, match:namespace waybar

# SwayNC
layerrule = blur on, ignore_alpha 0, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0.6, match:namespace swaync-notification-window

